name: Nightly Unit Tests

on:
  schedule:
    # Runs at 00:00 UTC every day (adjust cron syntax as needed)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # or your specific version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest2  # Only if you need this
        
    - name: Run unit tests
      run: |
        cd unit-tests  # Assuming your tests are in a unit-tests directory
        python -m unittest discover -v
