name: Nightly Unit Tests

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10","3.11", "3.12"]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies your tests need here
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        cd unit-tests  # Change this if your tests are in a different directory
        python -m unittest discover -v
      
    - name: Upload test results
      if: always()  # Upload results even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          unit-tests/test-reports/
          !unit-tests/test-reports/.gitkeep

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: '⚠️ Nightly tests failed on Python ${{ matrix.python-version }}!'})
    - name: Run tests with coverage
      run: |
        pip install coverage
        cd unit-tests
        coverage run -m unittest discover
        coverage xml
        coverage report -m

    - name: Upload coverage
      uses: codecov/codecov-action@v3
