name: Nightly Unit Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false  # Continue testing other versions if one fails
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        python -m unittest discover -s unit-tests/ -v || echo "::warning::Some tests failed (but continuing)"
    - name: Install coverage
      run: pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s unit-tests/ || echo "::warning::Some tests failed (but continuing)"
        coverage report -m
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          unit-tests/test-reports/
          !unit-tests/test-reports/.gitkeep
